//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from "axios";
import axios, { AxiosError } from "axios";

export class BurgerClient {
	protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
	private instance: AxiosInstance;
	private baseUrl: string;

	constructor(baseUrl?: string, instance?: AxiosInstance) {

		this.instance = instance ? instance : axios.create();

		this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:4000";

	}

	getAll(cancelToken?: CancelToken | undefined): Promise<Burger[]> {
		let url_ = this.baseUrl + "/api/burgers";
		url_ = url_.replace(/[?&]$/, "");

		let options_: AxiosRequestConfig = {
			method: "GET",
			url: url_,
			headers: {
				"Accept": "application/json",
			},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processGetAll(_response);
		});
	}

	protected processGetAll(response: AxiosResponse): Promise<Burger[]> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 200) {
			const _responseText = response.data;
			let result200: any = null;
			let resultData200 = _responseText;
			result200 = JSON.parse(resultData200);
			return Promise.resolve<Burger[]>(result200);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<Burger[]>(null as any);
	}
}

export class OrderClient {
	protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
	private instance: AxiosInstance;
	private baseUrl: string;

	constructor(baseUrl?: string, instance?: AxiosInstance) {

		this.instance = instance ? instance : axios.create();

		this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "http://localhost:4000";

	}

	getAll2(cancelToken?: CancelToken | undefined): Promise<Order[]> {
		let url_ = this.baseUrl + "/api/orders";
		url_ = url_.replace(/[?&]$/, "");

		let options_: AxiosRequestConfig = {
			method: "GET",
			url: url_,
			headers: {
				"Accept": "application/json",
			},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processGetAll2(_response);
		});
	}

	getForUser(user: string, cancelToken?: CancelToken | undefined): Promise<Order[]> {
		let url_ = this.baseUrl + "/api/orders/users/{user}";
		if (user === undefined || user === null)
			throw new Error("The parameter 'user' must be defined.");
		url_ = url_.replace("{user}", encodeURIComponent("" + user));
		url_ = url_.replace(/[?&]$/, "");

		let options_: AxiosRequestConfig = {
			method: "GET",
			url: url_,
			headers: {
				"Accept": "application/json",
			},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processGetForUser(_response);
		});
	}

	create(user: string, cancelToken?: CancelToken | undefined): Promise<Order> {
		let url_ = this.baseUrl + "/api/orders/users/{user}";
		if (user === undefined || user === null)
			throw new Error("The parameter 'user' must be defined.");
		url_ = url_.replace("{user}", encodeURIComponent("" + user));
		url_ = url_.replace(/[?&]$/, "");

		let options_: AxiosRequestConfig = {
			method: "POST",
			url: url_,
			headers: {
				"Accept": "application/json",
			},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processCreate(_response);
		});
	}

	delete(order: string, cancelToken?: CancelToken | undefined): Promise<void> {
		let url_ = this.baseUrl + "/api/orders/{order}";
		if (order === undefined || order === null)
			throw new Error("The parameter 'order' must be defined.");
		url_ = url_.replace("{order}", encodeURIComponent("" + order));
		url_ = url_.replace(/[?&]$/, "");

		let options_: AxiosRequestConfig = {
			method: "DELETE",
			url: url_,
			headers: {},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processDelete(_response);
		});
	}

	updateOrder(orderId: string, order: Order, cancelToken?: CancelToken | undefined): Promise<void> {
		let url_ = this.baseUrl + "/api/orders/{orderId}";
		if (orderId === undefined || orderId === null)
			throw new Error("The parameter 'orderId' must be defined.");
		url_ = url_.replace("{orderId}", encodeURIComponent("" + orderId));
		url_ = url_.replace(/[?&]$/, "");

		const content_ = JSON.stringify(order);

		let options_: AxiosRequestConfig = {
			data: content_,
			method: "PUT",
			url: url_,
			headers: {
				"Content-Type": "application/json",
			},
			cancelToken,
		};

		return this.instance.request(options_).catch((_error: any) => {
			if (isAxiosError(_error) && _error.response) {
				return _error.response;
			} else {
				throw _error;
			}
		}).then((_response: AxiosResponse) => {
			return this.processUpdateOrder(_response);
		});
	}

	protected processGetAll2(response: AxiosResponse): Promise<Order[]> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 200) {
			const _responseText = response.data;
			let result200: any = null;
			let resultData200 = _responseText;
			result200 = JSON.parse(resultData200);
			return Promise.resolve<Order[]>(result200);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<Order[]>(null as any);
	}

	protected processGetForUser(response: AxiosResponse): Promise<Order[]> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 200) {
			const _responseText = response.data;
			let result200: any = null;
			let resultData200 = _responseText;
			result200 = JSON.parse(resultData200);
			return Promise.resolve<Order[]>(result200);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<Order[]>(null as any);
	}

	protected processCreate(response: AxiosResponse): Promise<Order> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 201) {
			const _responseText = response.data;
			let result201: any = null;
			let resultData201 = _responseText;
			result201 = JSON.parse(resultData201);
			return Promise.resolve<Order>(result201);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<Order>(null as any);
	}

	protected processDelete(response: AxiosResponse): Promise<void> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 204) {
			const _responseText = response.data;
			return Promise.resolve<void>(null as any);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<void>(null as any);
	}

	protected processUpdateOrder(response: AxiosResponse): Promise<void> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && typeof response.headers === "object") {
			for (let k in response.headers) {
				if (response.headers.hasOwnProperty(k)) {
					_headers[k] = response.headers[k];
				}
			}
		}
		if (status === 204) {
			const _responseText = response.data;
			return Promise.resolve<void>(null as any);

		} else if (status !== 200 && status !== 204) {
			const _responseText = response.data;
			return throwException("An unexpected server error occurred.", status, _responseText, _headers);
		}
		return Promise.resolve<void>(null as any);
	}
}

export interface Burger {
	ingredients: string[];
	name: string;
}

export interface OrderBase {
	burgers: BurgerRecord[];
	user: string;
	date: string;
	drink?: Drink | undefined;
	fries?: Fries | undefined;
	dessert?: Dessert | undefined;
}

export interface Order extends OrderBase {
	id: string;
}

export interface BurgerRecord {
	name: string;
	excluded: string[];
	vegetarian: boolean;
	xl: boolean;
	comment?: string | undefined;
}

export enum Drink {
	Coca = "Coca",
	CocaZero = "CocaZero",
	IceTea = "IceTea",
	Limonade = "Limonade",
}

export interface Fries {
	sauces: Sauce[];
}

export enum Sauce {
	Ketchup = "Ketchup",
	Mayo = "Mayo",
}

export enum Dessert {
	Cookie = "Cookie",
	Brookie = "Brookie",
}

export class ApiException extends Error {
	override message: string;
	status: number;
	response: string;
	headers: { [key: string]: any; };
	result: any;
	protected isApiException = true;

	constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
		super();

		this.message = message;
		this.status = status;
		this.response = response;
		this.headers = headers;
		this.result = result;
	}

	static isApiException(obj: any): obj is ApiException {
		return obj.isApiException === true;
	}
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
	if (result !== null && result !== undefined)
		throw result;
	else
		throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any | undefined): obj is AxiosError {
	return obj && obj.isAxiosError === true;
}