version: "3"
services:
    coexya-sous-marin-jaune:
        container_name: "coexya-sous-marin-jaune"
        image: elyspio/coexya-sous-marin-jaune
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.json:/back/appsettings.json"
        networks:
            - external
            - internal
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.coexya-sous-marin-jaune-prefix.stripprefix.prefixes=/coexya/burgers"
            - "traefik.http.routers.coexya-sous-marin-jaune.middlewares=coexya-sous-marin-jaune-prefix@docker"
            - "traefik.http.routers.coexya-sous-marin-jaune.rule=PathPrefix(`/coexya/burgers`)"
            - "traefik.http.services.coexya-sous-marin-jaune.loadbalancer.server.port=4000"
            - "traefik.http.routers.coexya-sous-marin-jaune.entrypoints=external"

networks:
    external:
        external: true
    internal:
        external: true